# Occlusion Culling

In [50]:
from vedo import *
# settings.embedWindow(backend='ipyvtk', verbose = True)
import os
from ipyvtklink.viewer import ViewInteractiveWidget
import pykitti
from scene import scene
import numpy as np
%matplotlib notebook
%load_ext autoreload
%autoreload 2
%autosave 180

## init KITTI dataset -----------------------------------------------------------------
basedir = 'C:/kitti/'
date = '2011_09_26'
drive = '0005'
frame_range = range(150, 151, 1)
dataset = pykitti.raw(basedir, date, drive)
velo1 = dataset.get_velo(0) # Each scan is a Nx4 array of [x,y,z,reflectance]
cloud = velo1[:,:3]
# cloud = cloud[cloud[:,2] > -1.5] #ignore ground plane
## ------------------------------------------------------------------------------------


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Autosaving every 180 seconds


In [111]:
# c = cloud
c = np.random.randn(100,3)*np.array([20,20,1]) #test random points
S = scene(cloud = c, fid = 50)

ViewInteractiveWidget(S.plt.window)

ViewInteractiveWidget(height=960, layout=Layout(height='auto', width='100%'), width=960)

In [112]:
print(c)
print(S.grid[S.occupied])

[[ 2.18816464e+00 -6.96477511e+00 -1.01759721e+00]
 [-1.62047245e+01  3.48719493e+01  2.41378655e-01]
 [-5.05510621e+00 -2.99519341e+01 -7.12216043e-01]
 [ 2.41386244e+01 -4.01458234e+01  2.86106011e-01]
 [ 1.06389267e+01 -2.84039383e+01  1.13619693e+00]
 [-1.26050524e+01  6.69094006e-01  3.98333620e-01]
 [ 1.18372264e+01 -1.11638449e+01 -3.52239793e-01]
 [ 2.00808892e+01 -5.94685669e+00  6.18489737e-01]
 [-1.74586303e+01 -3.28646925e+01 -1.91398305e-01]
 [ 1.68422790e+00 -3.01272471e+01 -1.20029734e-01]
 [ 1.37115404e+01  1.80976925e+01 -7.14697590e-01]
 [ 7.59013349e+00  1.99464268e+01  3.06115511e-01]
 [-8.98753370e+00 -1.81596756e+01  9.93273310e-01]
 [ 1.23113612e+01 -1.18913199e+01 -5.99810269e-01]
 [-1.62987296e+01 -1.07791217e+01 -1.29749532e+00]
 [-1.76239671e+01 -1.34547133e+01 -3.94112666e-01]
 [-7.31309932e+00  1.09604597e+00  1.94205821e+00]
 [-7.05351499e-01 -2.58278483e+01 -1.37412873e+00]
 [-6.59543203e+01 -4.61287085e+00  7.56635464e-01]
 [-1.23328745e+01  1.09489068e+

In [84]:
print(mesh.__doc__)

Submodule to manage polygonal meshes.


In [ ]:
x1 = np.array([1,2,3])
x2 = np.array([5,6,7])
x3 = np.array([-1,-2,-3])

# mesh = np.meshgrid(x1)
mesh = np.mgrid[0:10:2, 0:10:2, 0:10:2].reshape(-1,3)
print(np.shape(mesh))
# print(mesh)

In [ ]:
"""Manually build a mesh from points and faces"""
from vedo import Mesh, printc, show

plt = Plotter(N=1, axes=2,bg = (1,1,1),  interactive=True)

verts = [(50,50,50), (70,40,50), (50,40,80), (80,70,50)]
faces = [(0,1,2), (2,1,3), (1,0,3)]
# (the first triangle face is formed by vertex 0, 1 and 2)

# Build the polygonal Mesh object:
mesh = Mesh([verts, faces])
mesh.backColor('violet').lineColor('tomato').lineWidth(2)
labs = mesh.labels('id').c('black')

# retrieve them as numpy arrays
printc('points():\n', mesh.points(), c=3)
printc('faces(): \n', mesh.faces(),  c=3)

show(mesh, labs, __doc__, viewup='z', axes=2).close()
# plt.show(disp)
ViewInteractiveWidget(plt.window)

In [ ]:
s  = 10*1j
np.mgrid[0:100:s]