In [1]:
import numpy as np
from matplotlib import pyplot as plt

C:\Users\Derm\anaconda3\envs\tf23\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Derm\anaconda3\envs\tf23\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\Derm\anaconda3\envs\tf23\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)


In [53]:
# Ground truth = [0.5, 0., 0., 0.0, 0.0, 0.01]
fn1 = "MC_results/s1_spherical_ICET_estimates.npy" 
fn2 = "MC_results/s1_spherical_ICET_pred_stds.npy"

# fn1 = "MC_results/s2_spherical_ICET_estimates_no_trees_with_rotation.npy" 
# fn2 = "MC_results/s2_spherical_ICET_pred_stds_no_trees_with_rotation.npy"

est = np.load(fn1)
pred_stds = np.load(fn2)

print(np.mean(pred_stds, axis = 0)[:3])
print(np.rad2deg(np.mean(pred_stds, axis = 0)[3:]))

# print(np.std(pred_stds, axis = 0)) #shows consistant prediction for soln std for constant scene

[0.00183839 0.00020515 0.00012555]
[0.0020247  0.00176425 0.00110244]


In [54]:
#calc mean and std
mean = np.mean(est, axis = 0)
std = np.std(est, axis = 0)

print(mean)
print(std[:3])
print(np.rad2deg(std[3:]))

[-4.98799649e-01  8.10841116e-05 -1.04727248e-04 -1.59457305e-06
  2.53975762e-05 -1.00026404e-02]
[0.0018876  0.00019527 0.00012981]
[0.00238716 0.00187576 0.00123174]
