In [1]:
import numpy as np
from matplotlib import pyplot as plt

C:\Users\Derm\anaconda3\envs\tf23\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Derm\anaconda3\envs\tf23\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\Derm\anaconda3\envs\tf23\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)


In [58]:
# 100 trials on same set of 2 frames (sensor noise re-applied for each trial)
# Ground truth = [0.5, 0., 0., 0.0, 0.0, 0.1]
fn1 = "MC_results/s1_spherical_ICET_estimates.npy" 
fn2 = "MC_results/s1_spherical_ICET_pred_stds.npy"

# fn1 = "MC_results/s2_spherical_ICET_estimates_no_trees_with_rotation.npy" 
# fn2 = "MC_results/s2_spherical_ICET_pred_stds_no_trees_with_rotation.npy"

est = np.load(fn1)
pred_stds = np.load(fn2)

print(np.mean(pred_stds, axis = 0)[:3])
print(np.rad2deg(np.mean(pred_stds, axis = 0)[3:]))

# print(np.std(pred_stds, axis = 0)) #shows consistant prediction for soln std for constant scene

[0.00179338 0.00020526 0.00012556]
[0.00202566 0.00176009 0.00109857]


In [74]:
#calc mean and std
mean = np.mean(est, axis = 0)
std = np.std(est, axis = 0)

print(mean)
print(std[:3])
print(np.rad2deg(std[3:]))

[-5.01104752e-01 -1.31759372e-04 -5.76142438e-05  4.64363280e-06
  2.50676512e-05 -9.99985662e-02]
[0.00210681 0.0002617  0.00011828]
[0.00196316 0.00172678 0.00110991]


In [82]:
#test - why does cov[0,0] give different results than std?????
#  answer: https://stackoverflow.com/questions/51923846/why-correlation-computed-by-nump-cov-and-np-std-is-different-from-the-result
# C = np.cov(est[:,0],est[:,1], ddof = 0) #need to include ddof arg
C = np.cov(est.T, ddof = 0) #need to include ddof arg
print(np.sqrt(abs(C)))

[[2.10680890e-03 6.27288063e-04 2.23612424e-05 5.36261049e-05
  5.75751343e-05 3.02715414e-05]
 [6.27288063e-04 2.61698970e-04 6.97642712e-05 3.34985040e-05
  1.86858160e-05 1.42138840e-05]
 [2.23612424e-05 6.97642712e-05 1.18280401e-04 1.74853437e-05
  1.80373831e-05 1.47248693e-05]
 [5.36261049e-05 3.34985040e-05 1.74853437e-05 3.42635735e-05
  8.86463461e-07 7.75656069e-06]
 [5.75751343e-05 1.86858160e-05 1.80373831e-05 8.86463461e-07
  3.01380137e-05 4.17262252e-06]
 [3.02715414e-05 1.42138840e-05 1.47248693e-05 7.75656069e-06
  4.17262252e-06 1.93715878e-05]]


In [136]:
#20 frame trajectory (3 iterations each pair)
# Ground truth = [0.5, 0., 0., 0.0, 0.0, 0.05]

# fn1 = "MC_results/traj1_spherical_ICET_estimates.npy" 
# fn2 = "MC_results/traj1_spherical_ICET_pred_stds.npy"
fn1 = "MC_results/traj2_spherical_ICET_estimates.npy" 
fn2 = "MC_results/traj2_spherical_ICET_pred_stds.npy"

est = np.load(fn1)
# print(est[:,0])
pred_stds = np.load(fn2)
# print(pred_stds[:,0])

print(np.mean(pred_stds, axis = 0)[:3], np.rad2deg(np.mean(pred_stds, axis = 0)[3:]))
# print(np.mean(pred_stds, axis = 0)[:3],np.mean(pred_stds, axis = 0)[3:])

[0.00113826 0.0009075  0.00036609] [0.00073703 0.00153429 0.00185816]


In [138]:
#calc mean and std
mean = np.mean(est, axis = 0)
print(mean)
std = np.std(est, axis = 0)

print(std[:3], np.rad2deg(std[3:]))
# print(std[:3], std[3:])

#TODO: don't just look at average STDs - use z scores to compare!

[ 5.00688359e-01  7.33457766e-04  4.24932203e-04  1.53245037e-05
 -1.89023582e-05 -4.99941625e-02]
[0.00101413 0.00093064 0.00033212] [0.00079302 0.00135996 0.00161694]


In [163]:
#test removing points too close to the center from scan2 in cartesian ICET
#   DEBUGGING GROUND PLANE NEAR EGO-VEHICLE

t = np.linspace(0,11,12)
t = t.reshape([4,3])
print(t, "\n")

# print(t[t<3])
dist = np.sum(t**2, axis = 1)
print(t[dist < 100])

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]] 

[[0. 1. 2.]
 [3. 4. 5.]]
