### Monte-Carlo sims for comparing D2D and DNN solution vectors



#### TODO:


Bring cartesian representation of corners back to training data generation file

Break test data into "easy, medium, and hard" scans with varying degrees of perspective shift


In [1]:
#setup
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import scipy.io as sio
import datetime

#need to have these two lines to work on my ancient 1060 3gb
#  https://stackoverflow.com/questions/43990046/tensorflow-blas-gemm-launch-failed
# physical_devices = tf.config.list_physical_devices('GPU') 
# tf.config.experimental.set_memory_growth(physical_devices[0], True)

print(tf.__version__) #requires tensorflow 2.3

%matplotlib notebook
%load_ext tensorboard
%load_ext autoreload
%autoreload 2
%autosave 180

2.9.1


Autosaving every 180 seconds


In [2]:
#Load data directly from numpy files-- KEEP IN RAM (DO NOT CONVERT TO TF Tensor!!!)
# #_________________________________________________________________
# #load individual data numpy files
# d1_1 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v1_scan1.npy")
# d2_1 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v1_scan2.npy")
# gt_1 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v1_ground_truth.npy")
# # d1_1 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v3_scan1.npy")
# # d2_1 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v3_scan2.npy")
# # gt_1 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v3_ground_truth.npy")

# # d1_1 = np.load("C:/Users/Derm/Desktop/big/pshift/scan1_300k_50_samples.npy")
# # d2_1 = np.load("C:/Users/Derm/Desktop/big/pshift/scan2_300k_50_samples.npy")
# # gt_1 = np.load("C:/Users/Derm/Desktop/big/pshift/ground_truth_300k_50_samples.npy")
# # gt_1 = gt_1*0.1 #scale to match real-world data (vel-> pos)

# # d1_2 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v2_scan1.npy")
# # d2_2 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v2_scan2.npy")
# # gt_2 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v2_ground_truth.npy")
# d1_2 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v4_scan1.npy")
# d2_2 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v4_scan2.npy")
# gt_2 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v4_ground_truth.npy")


# d1 = np.append(d1_1, d1_2, axis = 0)
# d2 = np.append(d2_1, d2_2, axis = 0)
# gt = np.append(gt_1, gt_2, axis = 0)
# #_________________________________________________________________

#Single datset
# d1 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v2_scan1.npy")
# d2 = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v2_scan2.npy")
# gt = np.load("C:/Users/Derm/Desktop/big/pshift/ICET_Ford_v2_ground_truth.npy")

# d1 = np.load("C:/Users/Derm/Desktop/big/pshift/scan1_300k_50_samples.npy")
# d2 = np.load("C:/Users/Derm/Desktop/big/pshift/scan2_300k_50_samples.npy")
# gt = np.load("C:/Users/Derm/Desktop/big/pshift/ground_truth_300k_50_samples.npy")
# gt = gt*0.1 #scale to match real-world data (vel-> pos)
#_________________________________________________________________

d1 = np.load("training_data/compact_scan1.npy")
d2 = np.load("training_data/compact_scan2.npy")
gt = np.load("training_data/compact_ground_truth.npy")
LUT = np.load("training_data/LUT.npy")
L = np.load("training_data/L.npy")
U = np.load("training_data/U.npy")
corn = np.load("training_data/corn.npy")
#_________________________________________________________________


#reshape but don't convert to tensor
points_per_sample = 50          #poitns sammpled from each voxel
tsplit = 0.5 #0.95                   #this fraction goes into training

scan1 = np.reshape(d1, [-1, points_per_sample, 3])
scan2 = np.reshape(d2, [-1, points_per_sample, 3])
ntrain = int(tsplit*tf.shape(scan1)[0].numpy())

x_train = np.append(scan1[:ntrain], scan2[:ntrain], axis = 1)
x_test = np.append(scan1[ntrain:], scan2[ntrain:], axis = 1)
print(np.shape(x_train))
print(np.shape(x_test))

y_train = gt[:ntrain] #for standard training/ test data
y_test = gt[ntrain:]
# y_train = gt[:ntrain][:,:,0] #when using compact data
# y_test = gt[ntrain:][:,:,0]
LUT = tf.convert_to_tensor(LUT)[ntrain:]
U = tf.convert_to_tensor(U)[ntrain:]
L = tf.convert_to_tensor(L)[ntrain:]
corn_train = corn[:ntrain]
corn_test = corn[ntrain:]

# print(y_train)
# print(np.shape(y_train))
# print(np.shape(y_test))
# print(np.shape(gt))
# print(np.shape(corn))
# print(corn)
#-------------------------------------------------------------------

(1471, 100, 3)
(1472, 100, 3)


In [3]:
# model = tf.keras.models.load_model("FORDNetV3.kmod")
model = tf.keras.models.load_model("FORDNetCP.kmod")

In [8]:
# DNN = model.predict(x_test[:10])
# print(DNN)
# print(tf.shape(y_test))
# print(tf.shape(x_test))
# print(tf.shape(LUT))
# print(tf.shape(U))
# print(tf.shape(L))

In [4]:
#define functions to convert between spherical and cartesian coordinate representations
def c2s(pts):
    """ converts points from cartesian coordinates to spherical coordinates """
    r = tf.sqrt(pts[:,0]**2 + pts[:,1]**2 + pts[:,2]**2)
    phi = tf.math.acos(pts[:,2]/r)
    theta = tf.math.atan2(pts[:,1], pts[:,0])

    out = tf.transpose(tf.Variable([r, theta, phi]))
    return(out)
def s2c(pts):
    """converts spherical -> cartesian"""

    x = pts[:,0]*tf.math.sin(pts[:,2])*tf.math.cos(pts[:,1])
    y = pts[:,0]*tf.math.sin(pts[:,2])*tf.math.sin(pts[:,1]) 
    z = pts[:,0]*tf.math.cos(pts[:,2])

    out = tf.transpose(tf.Variable([x, y, z]))
    # out = tf.Variable([x, y, z])
    return(out)

### Iterative solution for single test sample

In [6]:
n = int(np.floor(500*np.random.rand()))
# n = 0
print(n)

c1 = np.array([x_test[n,:points_per_sample,0], x_test[n,:points_per_sample,1], x_test[n,:points_per_sample,2]])
c2 = np.array([x_test[n,points_per_sample:,0], x_test[n,points_per_sample:,1], x_test[n,points_per_sample:,2]])

inputs = x_test[n][None,:]
runlen = 10
corr_sum = np.zeros([1,3]) #init var to store correction contributions
for i in range(runlen):
    correction = model.predict(inputs)[0] #show what the network thinks
#     correction = correction*0.1 #for synthetic matab data only??
#     correction = y_test[n] #show actual solution
    corr_sum += correction
    c1 = np.array([c1[0,:] + correction[0], c1[1,:] + correction[1], c1[2,:] + correction[2]])
    inputs = np.append(c1, c2, axis = 1).T[None,:,:]

print("\n correct soln", y_test[n])
print("\n estiamted soln:", corr_sum)
print("\n error from DNN:", y_test[n] - corr_sum)
mean1 = np.mean(x_test[n,:points_per_sample], axis = 0)
mean2 = np.mean(x_test[n,points_per_sample:], axis = 0)
print("\n error in means",  y_test[n] + (mean1 - mean2))

47
1/1 [==============================] - 0s 11ms/step

 correct soln [ 0.52963376 -1.5925289  -0.11975689]

 estiamted soln: [[ 0.51067625 -1.73462761 -0.16316545]]

 error from DNN: [[0.01895751 0.14209867 0.04340855]]

 error in means [0.00147319 0.00860536 0.02639726]


In [7]:
#use Vedo to plot inital and transformed point clouds in 3D 
from vedo import *
from ipyvtklink.viewer import ViewInteractiveWidget

plt1 = Plotter(N = 1, axes = 13, bg = (1, 1, 1), interactive = True)
disp = []

#draw scan1 
# disp.append(Points(x_test[n,:points_per_sample].numpy(), c = 'green', r = 5))
disp.append(Points(x_test[n,:points_per_sample], c = 'red', r = 5))

#draw initial scan2
# disp.append(Points(x_test[n,points_per_sample:].numpy(), c = 'red', r = 5))
disp.append(Points(x_test[n,points_per_sample:], c = 'blue', r = 5))

#Draw arrow for ground truth soln vec
disp.append(Arrow(mean1 + y_test[n], mean1, c = 'y4', res = 100)) #arbitrarily start arrow from scan1 center

#draw ground truth arrow cut short by U and L
soln_compact = tf.matmul(LUT[n], y_test[n][:, None])
soln_compact_xyz = tf.matmul(U[n], soln_compact)[:,0]
# soln_compact_xyz = tf.matmul(tf.transpose(U[n]), soln_compact)[:,0]
print(soln_compact_xyz)
disp.append(Arrow( mean2, mean2 - soln_compact_xyz, c = 'p4', res = 100)) #arbitrarily start arrow from scan1 center

#draw the set of 8 points that defined the voxel boundaries for the keyframe scan
corn_cart = s2c(corn_test[n])
# disp.append(Points(corn_cart, c = 'black', r = 10))

#draw box instead of individual points______________________________
p1, p2, p3, p4, p5, p6, p7, p8 = corn_cart.numpy()
print(p1)
print(p2)
lineWidth = 2
c1 = "black"

arc1 = shapes.Line(p1, p2, c = c1, lw = lineWidth) 
disp.append(arc1)
arc2 = shapes.Line(p3, p4, c = c1, lw = lineWidth) #debug
disp.append(arc2)
line1 = shapes.Line(p1, p3, c = c1, lw = lineWidth)
disp.append(line1)
line2 = shapes.Line(p2, p4, c = c1, lw = lineWidth) #problem here
disp.append(line2)
arc3 = shapes.Line(p5, p6, c = c1, lw = lineWidth) #debug
disp.append(arc3)
arc4 = shapes.Line(p7, p8, c = c1, lw = lineWidth) #debug
disp.append(arc4)
line3 = shapes.Line(p5, p7, c = c1, lw = lineWidth)
disp.append(line3)
line4 = shapes.Line(p6, p8, c = c1, lw = lineWidth)
disp.append(line4)
disp.append(shapes.Line(p1,p5, c = c1, lw = lineWidth))
disp.append(shapes.Line(p2,p6, c = c1, lw = lineWidth))
disp.append(shapes.Line(p3,p7, c = c1, lw = lineWidth))
disp.append(shapes.Line(p4,p8, c = c1, lw = lineWidth))
#_____________________________________________________________________

#draw transformed scan2
# disp.append(Points(c1, c = 'blue', r = 5))

plt1.show(disp, "Network Performance Test")
ViewInteractiveWidget(plt1.window)


tf.Tensor([ 0.53243005  0.00128222 -0.05259839], shape=(3,), dtype=float32)
[ 4.709242   -3.4214644   0.20789552]
[ 4.9969807  -2.9855585   0.20789552]


ViewInteractiveWidget(height=960, layout=Layout(height='auto', width='100%'), width=960)

### Run network on all test data

In [8]:
# for n in range(numToTest):
c1 = np.array([x_test[:,:points_per_sample,0], x_test[:,:points_per_sample,1], x_test[:,:points_per_sample,2]])
c2 = np.array([x_test[:,points_per_sample:,0], x_test[:,points_per_sample:,1], x_test[:,points_per_sample:,2]])
c1 = np.transpose(c1, (1,2,0))
c2 = np.transpose(c2, (1,2,0))

inputs = x_test
# print("c1" , tf.shape(c1))
print("x_test" , tf.shape(x_test))
runlen = 10
corr_sum = np.zeros([tf.shape(x_test)[0].numpy(),1,3]) #init var to store correction contributions
for i in range(runlen):
    correction = model.predict(inputs)[:,None,:] #show what the network thinks
#     correction = correction*0.1 #for synthetic matab data only??
#     correction = y_test[n] #show actual solution
    corr_sum += correction
#     print("corr_sum", tf.shape(corr_sum))
    c1 += correction
#     print("after correction", tf.shape(c1))
    inputs = np.append(c1, c2, axis = 1)#.T
#     print("\n new inputs", tf.shape(inputs))
    
dnn_estimates = corr_sum[:,0,:]
print("\n correct soln \n", y_test)
print("\n estiamted soln: \n", dnn_estimates)
print("\n error from DNN: \n", y_test - dnn_estimates)

print("\n mean raw DNN error: \n", np.sqrt(np.sum(np.mean(np.abs(y_test - dnn_estimates), axis = 0)**2)))

D2D_distance = np.mean(x_test[:,:points_per_sample], axis = 1) - np.mean(x_test[:,points_per_sample:], axis = 1)
# print(tf.shape(D2D_distance))
# print(tf.shape(y_test))
print("\n mean raw D2D error \n", np.sqrt(np.sum(np.mean(np.abs(y_test + D2D_distance), axis = 0)**2 )))

x_test tf.Tensor([1472  100    3], shape=(3,), dtype=int32)
46/46 [==============================] - 0s 2ms/step

 correct soln 
 [[-1.5052794  -0.061748   -0.02118067]
 [-0.72679394 -0.54963243  0.05901803]
 [ 0.2958136   0.4468636  -0.04729297]
 ...
 [ 0.01318293  1.3810297  -0.04743544]
 [-1.8122277  -1.8693733  -0.04297731]
 [-0.7231753   0.3887675  -0.00653277]]

 estiamted soln: 
 [[-1.58495105 -0.07757852 -0.01402593]
 [-0.80877191 -0.59026881  0.02493609]
 [ 0.13410813  0.41948672 -0.06199452]
 ...
 [ 0.08477809  1.34650388 -0.0826522 ]
 [-1.8182852  -1.85418773 -0.02040547]
 [-0.72365818  0.34285385 -0.32680475]]

 error from DNN: 
 [[ 0.07967163  0.01583052 -0.00715474]
 [ 0.08197797  0.04063638  0.03408195]
 [ 0.16170546  0.02737688  0.01470155]
 ...
 [-0.07159516  0.03452585  0.03521677]
 [ 0.00605747 -0.01518559 -0.02257183]
 [ 0.00048289  0.04591366  0.32027198]]

 mean raw DNN error: 
 0.12247131528202262

 mean raw D2D error 
 0.051821


In [9]:
#just considering the residuals doesn't tell the whole story 
#   we need to consider error in COMPACT only directions

#use LUT to get compact axis of DNN solution vec for each trial
dnn_compact = tf.matmul(LUT, dnn_estimates[:,:,None])
dnn_compact_xyz = tf.matmul(U, dnn_compact)

#for distrubution means distance
d2d_compact = tf.matmul(LUT, D2D_distance[:,:,None])
d2d_compact_xyz = tf.matmul(U, d2d_compact)

truth_compact = tf.matmul(LUT, y_test[:,:,None])
truth_compact_xyz = tf.matmul(U, truth_compact)

error_DNN_compact = np.sqrt(np.sum( np.mean(np.abs(truth_compact_xyz - dnn_compact_xyz), axis = 0)**2 ))
print("\n mean compact error DNN: \n", error_DNN_compact)

error_D2D_compact = np.sqrt(np.sum( np.mean(np.abs(truth_compact_xyz + d2d_compact_xyz), axis = 0)**2 ))
print("\n mean compact error D2D: \n", error_D2D_compact)




 mean compact error DNN: 
 0.058368146

 mean compact error D2D: 
 0.014100906


In [15]:
s2c(corn_test[n])

<tf.Tensor: shape=(8, 3), dtype=float32, numpy=
array([[ 6.597618  , -3.177247  ,  0.78728276],
       [ 6.8558645 , -2.57305   ,  0.78728276],
       [ 7.220676  , -3.4772959 ,  0.8616312 ],
       [ 7.50331   , -2.8160405 ,  0.8616312 ],
       [ 6.6314106 , -3.1935205 ,  0.2628742 ],
       [ 6.89098   , -2.5862288 ,  0.2628742 ],
       [ 7.2576594 , -3.4951062 ,  0.2876992 ],
       [ 7.5417414 , -2.8304641 ,  0.2876992 ]], dtype=float32)>